# Use root/example as user/password credentials
version: "3.8"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: salmon2289
      MYSQL_ROOT_PASSWORD: 123456789
    ports:
      - "3307:3306"
# Docker là nơi chứa DataBase, muốn connect tới DB thì phải TURN ON DOCKER
# DBeaver là phần trung gian để connect giữa Docker DB & Môi trường dev
# Không Update Docker để tránh lỗi
